### PR TITLE
Add Mobile Accessibility / ITP

### PR DESCRIPTION
**Pull request by thibmaek**
Let me know if this needs any additional changes :)

### CODE REVIEW

**Comment by robinclaes** [comment]
Hello @thibmaek, thanks for submitting a PR!

.png screenshots are not supported right now.

If the app is on the app or play store you can use .webp images uploaded there:
image

If it is not (which I don't think it is?) you can convert any (separate) screenshot from png to webp.

Let me know if I can help in any way 🙏 Feel free to poke me on [our discord server](https://discord.gg/U5gYN6juNx)

**Comment by thibmaek** [comment]
A PR template would greatly help avoid hitting CI with easy to solve errors every time here.
Think you best squash this

**Comment by robinclaes** [comment]
@thibmaek nearly there! 

The screenshots need to be 16:9 so each screenshot .webp-file has to be an individual screen.

**Comment by robinclaes** [comment]
Hi @thibmaek , it's been a while. Let me know if I can help with moving this PR forward.
I'll make sure to add a PR template and some other helpful ways to make the process less painful.
Thanks for your feedback!

**Pull request closed without merging**
